// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASmb5YqNqDCv9VtWBdpEzQfuiZRwijzm0',
    appId: '1:1016185258944:web:5dae86817116c240577e25',
    messagingSenderId: '1016185258944',
    projectId: 'lg-dx-school',
    authDomain: 'lg-dx-school.firebaseapp.com',
    storageBucket: 'lg-dx-school.firebasestorage.app',
    measurementId: 'G-S7J5EQSDY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMP6v6hpDdXvnaEx4vCMoInzWb1QQpGRo',
    appId: '1:1016185258944:android:7e7ea5f9b801bb3e577e25',
    messagingSenderId: '1016185258944',
    projectId: 'lg-dx-school',
    storageBucket: 'lg-dx-school.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjwDgv3BFxWyzrsFBHbnEDsAsejklZ-gE',
    appId: '1:1016185258944:ios:2ae1b55c36f58e42577e25',
    messagingSenderId: '1016185258944',
    projectId: 'lg-dx-school',
    storageBucket: 'lg-dx-school.firebasestorage.app',
    iosBundleId: 'com.lgdxschool.instagram',
  );
}
